title = "Eloquent Programmer"
baseURL = "/"
languageCode = "en-us"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
googleAnalytics = ""
enableRobotsTXT = true

[permalinks]
  "post" = "/:year/:month/:title"

[params]
  description = "Where you learn to be a better programmer" # Description of the page less than 150 characters
  facebook = "https://www.facebook.com/eloquent.programmer"
  twitter = "https://twitter.com/eloqprogrammer"
  instagram = "https://www.instagram.com/eloquentprogrammer/"
  github = "https://github.com/eloquent-programmer"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = -110

  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about"
    weight = -100

  
