title = "Eloquent Programmer"
baseURL = "https://eloquentprogrammer.com"
languageCode = "en-us"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
googleAnalytics = "UA-178442559-1"
enableRobotsTXT = true

[permalinks]
  "post" = "/:year/:month/:title"

[params]
  description = "Where you learn to be a better programmer" # Description of the page less than 150 characters
  facebook = "https://www.facebook.com/eloquent.programmer"
  twitter = "https://twitter.com/eloqprogrammer"
  instagram = "https://www.instagram.com/eloquentprogrammer/"
  github = "https://github.com/eloquent-programmer"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = -110

  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about"
    weight = -100

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true

  
